### ISSUE TITLE
allow using return to change state

### ISSUE THREAD

**Issue by torontofangirl** [sohomsahaun/SnowState#14]
Consider allowing 
```
if (HDIR != 0) return "run";
```
instead of
```
if (HDIR != 0) {
  state.change("run");
  return;
}
```

Using `return` to indicate the new state is much more convenient, since:
- You don't need to type out both curly braces
- You don't need to type out state.change

`state.change` can still be kept to have custom enter/leave events, or to run the whole event before changing.

It could be renamed to `state.change_with`

**Comment by sohomsahaun** [comment]
For the first point, you can just say:
```
if (HDIR != 0) return state.change("run");
```
I believe that's convenient enough.
