### ISSUE TITLE
Just a couple of small typos in the documentation.

### ISSUE THREAD

**Issue by JohnPeppermint** [sohomsahaun/SnowState#19]
![image](https://user-images.githubusercontent.com/44186303/137996420-73809ca3-a268-4bcb-bfb1-92e0808898fe.png)

https://github.com/sohomsahaun/SnowState/wiki/Event

Probably should say "Step" where it says "Enter" in the first paragraph.

and... 

![image](https://user-images.githubusercontent.com/44186303/137996643-c9934c47-6efc-4949-81d7-08131a8ac9a0.png)

There's a small typo there where it says "event_inhertied()." instead of event_inherited().
https://github.com/sohomsahaun/SnowState/wiki/SnowState

I just thought I might as well report them.

Awesome library, by the way, I love it! Cheers.

**Comment by sohomsahaun** [comment]
Thank you for pointing out, fixed! :)
