### ISSUE TITLE
Curious about a specific line

### ISSUE THREAD

**Issue by PeterPanen** [sohomsahaun/SnowState#2]
Sorry for creating an Issue about this, but i am very excited about your state machine, and was wondering what the purpose of this specific line is.
Thanks in advance!

https://github.com/sohomsahaun/SnowState/blob/afe5f8e584ffc90ba97f48f36f21725009c48b02/scripts/SnowState/SnowState.gml#L49

**Comment by sohomsahaun** [comment]
Hey!
The purpose is already explained in the [wiki](https://github.com/sohomsahaun/SnowState/wiki#documentation).
Removing the line would pop up "function expects x arguments" for functions using optional arguments. Which is... fine, but it feels better with lesser useless warnings.
Hopefully, YYG will fix this soon.

**Comment by PeterPanen** [comment]
Thank you!
I knew i missed something lol
