### ISSUE TITLE
Assignment of an empty value - When running using YYC

### ISSUE THREAD

**Issue by VeroSquirrel** [sohomsahaun/SnowState#27]
The framework works perfectly fine when running with VM, however, as soon as I clear the project and compile it using YYC, I get the following compile time exception:

Script: SnowState at line 327 : Assignment of an empty value (function does not return anything?)

Once again, everything works perfectly fine with VM, and all of my functions in the add_transition functions return something, no matter what.

UPDATE: Same thing happens in the included DEMO project, if run using YYC.

GMS2 version: 2022.3.0.625
Runtime version: 2022.3.0.497
SnowState version: v3.1.0

**Comment by sohomsahaun** [comment]
Looks like a YYC issue. Fixed in v3.1.1.
Thanks for reporting!
