### ISSUE TITLE
Beta Variable not set before reading error

### ISSUE THREAD

**Issue by tkhris** [sohomsahaun/SnowState#31]
On the beta to use new rollback. From what I can tell SnowState should work with it but getting an error 

_____
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_player:

Variable struct.event(100060, -2147483648) not set before reading it.
 at gml_Script_anon_anon_SnowState_gml_GlobalScript_SnowState_4416_SnowState_gml_GlobalScript_SnowState_4532_anon_SnowState_gml_GlobalScript_SnowState_4416_SnowState_gml_GlobalScript_SnowState (line 159) -                      exec(event, undefined, _args);
############################################################################################
gml_Script_anon_anon_SnowState_gml_GlobalScript_SnowState_4416_SnowState_gml_GlobalScript_SnowState_4532_anon_SnowState_gml_GlobalScript_SnowState_4416_SnowState_gml_GlobalScript_SnowState (line 159)
gml_Object_obj_player_Step_0 (line 9) - fsm.step();

**Comment by tkhris** [comment]
I am on the beta version here https://gms.yoyogames.com/ReleaseNotes-NuBeta.html Version 2022.800.0.180

**Comment by sohomsahaun** [comment]
Unfortunately, GM's rollback netcode is still unstable so it is not supported as of now. v4 will have some features for easier integration of SnowState with netcode though.
