### ISSUE TITLE
Allow an option to not trigger enter/leave events using the change() method

### ISSUE THREAD

**Issue by patchuby** [sohomsahaun/SnowState#34]
It would be useful for cases where I'm changing to a state regardless of the current state, but I might not want to trigger enter/leave events if I'm changing to my current event (going from state "A" to state "A"). 
I can do this currently by checking the current state before switching but it could be nice to have an optional argument in the change method, or a config option when setting up the state machine.

**Comment by sohomsahaun** [comment]
You can override the events. This is what I'd do:

```js
function noop() {} // Do nothing

fsm.change("A", noop, noop);
```
