### ISSUE TITLE
When running the game after downloading get move_and_collide is a read-only function

### ISSUE THREAD

**Issue by SitKneesweak** [sohomsahaun/SnowState#36]
Looks great piece of software but getting this on runtime:

Object: oPlayerT Event: User Event 15 at line 53 : "move_and_collide" is read-only function
Object: oPlayerD Event: User Event 15 at line 47 : "move_and_collide" is read-only function
Object: oPlayerT Event: User Event 15 at line 53 : malformed assignment statement
Object: oPlayerD Event: User Event 15 at line 47 : malformed assignment statement

On Mac v 2023.1

thanks

**Comment by sohomsahaun** [comment]
It is because the demo project has been using a `move_and_collide` method and GameMaker very recently introduced a built-in `move_and_collide` function.
You can Ctrl+Shift+F for `move_and_collide` and replace every instance of it with `move_and_collide_` or anything you wish.

**Comment by SitKneesweak** [comment]
Ah OK thanks for responding.

As an aside, I’m refactoring my game code using your snowstate project as a template but where I create the struct for input (input{}), Gamemaker always asks me to define the variables on runtime. In your project it’s empty. How did you get it to do this as when I give my various inputs initial variables of 0 it means my character doens’t move!)

Any guidance appreciated!
Henry

**Comment by sohomsahaun** [comment]
It might show you a warning, but you can turn it off. It won't affect the gameplay.

From the info you have given, it sounds like you are only defining the inputs once. You have to check them in one of the Step events to work every step.

If you need GML help, I highly recommend joining the GameMaker Discord server.
Link: [GameMaker Discord](https://discord.gg/gamemaker)

**Comment by SitKneesweak** [comment]
Thanks for getting back. It wants me to define check_input() at game start. When I don’t it brings back:

Variable <unknown_object>.check_input(100258, -2147483648) not set before reading it.
 at gml_Object_obj_player_Create_0 (line 43) - check_input();

check_input() is in create and step events.


Sorry for the basic questions!

**Comment by SitKneesweak** [comment]
sorry, I found it, event_user, I’ll get my coat…

Superlative programme by the way, I’m learning a lot and my game is improving.

**Comment by sohomsahaun** [comment]
Great, thank you!
Marking the issue as solved.
