### ISSUE TITLE
HTML5 support is broken

### ISSUE THREAD

**Issue by IsaacTCB** [sohomsahaun/SnowState#41]
SnowState crashes on HTML5 with the latest version of GameMaker.

It has something to do with GM's built-in `method()` function not receiving a proper function, as it causes the exception:
*"method : argument needs to be a function"*.

I tested a clean project with SnowState (code below) and the SnowState demo (I had to fix _move_and_collide_ naming collision for it to build), neither of which worked.

Here's the code I used for the clean project:
```
/// Create Event
state  = new SnowState("test");
state
	.add("test", {
		enter:  function() {
			show_debug_message("Entering");
		},
		
		step: function() {
			x = mouse_x;
			y = mouse_y;
		},
		
		leave: function() {
			show_debug_message("Leaving");	
		}
	})
	
/// Step Event
state.step();
```
I tested Chromium-based browsers and Firefox.

**Comment by sohomsahaun** [comment]
This is a bug in GM's HTML5, where `variable_struct_get_names` returns weird values. The solution is to ignore keys starting with `___struct___`, like:

```gml
/// @param {struct} state_struct
/// @return {struct} Struct filled with all possible events
__create_events_struct = function(_struct) {
	var _events = {};
	var _arr, _i, _event, _defEvent;
			
	_arr = variable_struct_get_names(_struct);
	_i = 0; repeat(array_length(_arr)) {
		_event = _arr[_i];
		if (string_pos("___struct___", _event) != 1) {
			__assert_event_name_valid(_event);
			__assert_event_available(_event);
			_events[$ _event] = {
				exists: SNOWSTATE_EVENT.DEFINED,
				func: method(__owner, _struct[$ _event])
			};
		}
		++_i;
	}
		
	_arr = variable_struct_get_names(__defaultEvents);
	_i = 0; repeat(array_length(_arr)) {
		_event = _arr[_i];
		if (string_pos("___struct___", _event) != 1) {
			_defEvent = __defaultEvents[$ _event];
			if (!variable_struct_exists(_struct, _event)) {
				_events[$ _event] = {
					exists: _defEvent.exists,
					func: method(__owner, _defEvent.func)
				};
			}
		}
		++_i;
	}
		
	return _events;
};
```

**Comment by sohomsahaun** [comment]
Here is a version of `SnowState.gml` we use for HTML5. If you search for `___struct___` in the script, you can see the changes.

[SnowState.txt](https://github.com/sohomsahaun/SnowState/files/13709698/SnowState.txt)
