### ISSUE TITLE
Object: oPlayerT Event: User Event 15 at line 53 : "move_and_collide" is read-only function in latest GameMaker monthly version

### ISSUE THREAD

**Issue by allende** [sohomsahaun/SnowState#42]
I'm getting this message when opening in latest GameMaker monthly version (2023.11.1.129 runtime 2023.11.1.160) 
and trying to run it.

Object: oPlayerT Event: User Event 15 at line 53 : "move_and_collide" is read-only function
Object: oPlayerD Event: User Event 15 at line 47 : "move_and_collide" is read-only function
Object: oPlayerT Event: User Event 15 at line 53 : malformed assignment statement
Object: oPlayerD Event: User Event 15 at line 47 : malformed assignment statement

GM Version
![image](https://github.com/sohomsahaun/SnowState/assets/662577/9f7271b9-4ec1-4f13-89ec-3c626557cb5e)

Temporary fix (at least I was able to run it) search and replace all 
serach:move_and_collide
replace:_move_and_collide

![image](https://github.com/sohomsahaun/SnowState/assets/662577/82429ac0-d4fd-4c7a-8225-6976292fe18d)

Wondering if its a case where GM actually implemented the function move_and_collide in a later version

**Comment by offalynne** [comment]
> Wondering if its a case where GM actually implemented the function move_and_collide in a later version

yep

**Comment by michaelwschultz** [comment]
If you just rename the function to something else `move_and_collide_custom`, plus all the references, things should build just fine.
